# Update-Version.ps1
# Pre-build hook called by ClarionAssistant.csproj.
# 1. Reads Version.props
# 2. Increments VersionBuild by 1 (unless -NoIncrement is passed). FullVersion is NOT touched --
#    it is the released Major.Minor.Patch and must keep matching the git tag.
# 3. Writes Version.props back
# 4. Regenerates Properties\AssemblyVersion.cs and ClarionAssistant.addin from templates
#
# All generation is idempotent: if the source-controlled artifacts (.addin.template, etc.)
# are unchanged and version is unchanged, output is byte-identical.

param(
    [switch]$NoIncrement
)

$ErrorActionPreference = 'Stop'

$ScriptDir       = $PSScriptRoot
$VersionProps    = Join-Path $ScriptDir 'Version.props'
$AddinTemplate   = Join-Path $ScriptDir 'ClarionAssistant.addin.template'
$AddinOut        = Join-Path $ScriptDir 'ClarionAssistant.addin'
$AssemblyVerOut  = Join-Path $ScriptDir 'Properties\AssemblyVersion.cs'

if (-not (Test-Path $VersionProps))   { throw "Version.props not found: $VersionProps" }
if (-not (Test-Path $AddinTemplate))  { throw "Addin template not found: $AddinTemplate" }

# --- Read current version ---
[xml]$xml = Get-Content -LiteralPath $VersionProps -Raw
$pg = $xml.Project.PropertyGroup
$major = [int]$pg.VersionMajor
$minor = [int]$pg.VersionMinor
$patch = [int]$pg.VersionPatch
$build = [int]$pg.VersionBuild

# --- Increment build (unless suppressed) ---
# Only VersionBuild moves here. FullVersion (Major.Minor.Patch) is the RELEASED version and is
# bumped by hand via Bump-Version.ps1 -- it has to stay equal to the git tag and to the manifest's
# <Identity version>, so a compile must never change it. See the comment in Version.props.
if (-not $NoIncrement) {
    $build = $build + 1
    $pg.VersionBuild = "$build"
    # Recompute derived properties so they stay in sync inside Version.props
    $pg.FullVersion         = "$major.$minor.$patch"
    $pg.AssemblyFullVersion = "$major.$minor.$patch.$build"
    $xml.Save($VersionProps)
}

$fullVersion     = "$major.$minor.$patch"
$assemblyVersion = "$major.$minor.$patch.$build"

Write-Host "ClarionAssistant version: $fullVersion" -ForegroundColor Cyan

# --- Generate Properties\AssemblyVersion.cs ---
$asmDir = Split-Path -Parent $AssemblyVerOut
if (-not (Test-Path $asmDir)) { New-Item -ItemType Directory -Path $asmDir | Out-Null }

$asmContent = @"
// <auto-generated>
// Generated by Update-Version.ps1. Do not edit — edit Version.props instead.
// </auto-generated>
using System.Reflection;

[assembly: AssemblyVersion("$assemblyVersion")]
[assembly: AssemblyFileVersion("$assemblyVersion")]
[assembly: AssemblyInformationalVersion("$fullVersion")]
"@

# Only write if changed (avoid touching mtime + triggering rebuilds unnecessarily)
$existing = if (Test-Path $AssemblyVerOut) { Get-Content -LiteralPath $AssemblyVerOut -Raw } else { '' }
if ($existing -ne $asmContent) {
    Set-Content -LiteralPath $AssemblyVerOut -Value $asmContent -NoNewline -Encoding UTF8
}

# --- Generate ClarionAssistant.addin from template ---
$tpl = Get-Content -LiteralPath $AddinTemplate -Raw
$out = $tpl -replace '@VERSION@', $fullVersion
$existingAddin = if (Test-Path $AddinOut) { Get-Content -LiteralPath $AddinOut -Raw } else { '' }
if ($existingAddin -ne $out) {
    Set-Content -LiteralPath $AddinOut -Value $out -NoNewline -Encoding UTF8
}
